### ISSUE TITLE
Discover: as all kirigami apps should do, allow grab'n'swipe of the content area (either via finger or mouse)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#109]
compare how in "dash menu - all applications" the area can be grabbed and swiped upwards or downwards

btw. that was working fine in previous Discover before.

**Comment by notmart** [comment]
There are several implementations of scrollviews, that is because QtQuickControls2 used to not have one, now QtQuickControls2 recently got one, which will eventually become the only implementation as upstream Qt, and kirigami has one which is used in few places (as we can't yet depend from that Qt version)
Now, i changed the one internal in Kirigami to try to at the same time keep the flicking enabled and our custom mouse wheel management (to counter all the "mouse wheel is slow" problems), so it should work now similar as before again, for some things such as the Discover main scrollable pages.

*But* the upstream QtQuickControls2 scrollview, which a lot of application will use, explicitly disables this grab and swipe behavior for the mouse by purpose (while continues to work with a real touchscreen), for the rationale that this is a touchscreen specific feature and a real mouse shouldn't do touchscreen specific behaviors as usually that gesture means something different on a desktop, which i tend to agree to.
For instance on a file manager click+drag means selecting files with the rubberband when done on an empty area and drag and drop of items when done over a file icon, some start menus also do prefer drag and drop of items over dragging the view. The two things can't be supported together on the same input device(mouse).

So, for now, things like the main view in discover will support scrolling by dragging (done in master) but many other item views will support that only with real touch screens. a change in upstream Qt can be proposed, but is probably something too likely to cause bugs, which wouldn't be accepted.

**Comment by star-buck** [comment]
For kirigami, we may like to identify the parts of where a scrollview is
used and it makes sense to always have the flicking possibility for those
parts even with a present mouse, as screens and laptops become increasingly
"mixed mode" touchfriendly while having an additional mouse or touchpad
present, since doing things directly on screen is more convenient.

**Comment by notmart** [comment]
i've made it working with a mouse everywhere i could, so in the main areas of kirigami apps, it would have grab and flick working with a mouse everywhere.
Note that interaction of touch and drag will always work everywhere with a proper touchscreen, even with a mouse connected. on my laptop all scroll areas, even those coming from qtquickcontrols2 support it when i interact with them with the touch screen, so the use case of hybrid devices is covered.
