### ISSUE TITLE
Favorites: after changing the menu back and forth again, Favorites change back to kde defaults

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#187]
having some favorites other than the default set and changing the menu does seem to reset the favs to the defaults. Experienced in current Netrunner Rolling.
initial favorites when starting netrunner:
![Screenshot_20190410_222312](https://user-images.githubusercontent.com/840070/55911101-3d414380-5be0-11e9-854f-62711d2bbe3c.png)

after trying an alternative menu and switching back:
![Screenshot_20190410_142022](https://user-images.githubusercontent.com/840070/55878023-d8fc9080-5b9b-11e9-8510-5ed2200c0ca6.png)

**Comment by star-buck** [comment]
it is common: add or remove a favorite, change menu to something else via alternatives, switch back to previous menu: favorites are reset.
Expected behaviour would be to have them kept and shown again.
Bonus if favorites were actually synced to other menus.
A minimum solution would be how to set Favorites per install/distro and not have them reset or overridden by kde defaults (either Netrunner does it wrong or there could be a way to alter th defaults itself differently/in a way they do no longer override the distros initial set?)

**Comment by eikehein** [comment]
This ticket is a bit like time travel / surprising. Both of these things got implemented years ago, by Blue Systems for Blue Systems. We have per-applet init scripts support in LnF packages for vendor defaults, and we have shared favorites via the Activities db.

If it's not working it's a bug or a menu using the wrong API. I need more detailed steps to reproduce (e.g. switching from which version of which menu to which version of which menu).

**Comment by star-buck** [comment]
Imo you can try with any menu to any menu yourself.

**Comment by eikehein** [comment]
I change menus a couple of times per week and have the same favorites in all of them :) There's definitely more to this ...

**Comment by star-buck** [comment]
Then its the distros like e.g. latest Manjaro, where you have the default
favorites loaded. You remove e.g. Kate, switch to Kicker, switch back to
Kickoff and have Kate there again.

**Comment by llelectronics** [comment]
> You remove e.g. Kate, switch to Kicker, switch back to
Kickoff and have Kate there again.

This is intended. It will load whatever is set as default. Though the issue is that somehow the LNF is not loaded correctly so it is not applying the favorites from the LNF scripts. 
Or is it mixing both LNF scripts favorites with default ones? 
I am still not getting the whole issue but I remember seeing such a behavior when we changed LNF themes in Netrunner Desktop and not all configuration files were set to use this LNF. 
Also are activities maybe interfering aswell?

**Comment by eikehein** [comment]
Right, I think I am starting to grasp what's going on. Ivan wrote all of this code, so I'm not super familiar with it. Here's what I think happens:

* The menu plasmoids have a default config of favorites, either in the upstream source or in an LnF setup script like James wrote them
* When a plasmoid is created (switching via Alternatives just destroys and creates plasmoids), it ports the favorites from its config to the KActivities database and makes a note that it was ported

"When a plasmoid is created" is a subtle issue: It happens when switching plasmoids via Alternatives, but it also happens when just logging into Plasma (all the plasmoids the user has added get created). So the code doesn't do "there's already favorites in the KActivities db; do nothing". Because it also needs to handle the case when a user upgrades from a Plasma version that doesn't store favorits in the KActivities database to a version that does. I.e. imagine you have three menus in different panels, with different favorites: This migration code will add all their favorites to the database (avoiding duplicates) so you don't lose any.

The effect is that if you remove a favorite from the default set and then switch menus (creating a new plasmoid), the migration code runs and adds it back.

I've never noticed this personally because I've never removed a favorite from the Plasma upstream default set, just added additional ones.

I can see what Ivan was trying to do there and why it is like this, but I agree this is a problem. Finding a solution is a bit tricky, I need to think about it for a while.

(I also originally misunderstood the first post in this ticket. I thought it was about favorites disappearing, but it's about removed ones reappearing.)

But to be clear, all of the "favorites syncing between menus" etc. is there and works fine otherwise.

**Comment by star-buck** [comment]
Yes, when switching menus the menu does not pick up the lnf default ones ,
but mixes in the kde default ones as well, which is a slight seperate
issue. This should not be the case.
The other case is if a user e.g. removes a favorite regardless of the
distro defined one or the kde default ones in a menu, those favs should be
stored and synced and taken. It annyos to no end when picking e.g. chrome
as user and ending up with firefox or whatever a distro or kde thinks are
good defaults only by switching to an alternative menu.

**Comment by eikehein** [comment]
Luckily the default favorite for the web browser is smart and automatically adjusts to whatever the user sets as default browser.

I agree though that removing a default favorite should be synced as well. It's a design flaw in Ivan's code that needs fixing.

**Comment by star-buck** [comment]
@eikehein: Thanks for looking into it!

**Comment by star-buck** [comment]
@pointedstick: do we need a phab ticket for it?

**Comment by eikehein** [comment]
Next week I think I'll be super busy churning out code on Valve (we got to make progress), but toward later this months I could find some headspace to try and design a solution approach to this. How does that sound?

**Comment by star-buck** [comment]
Sounds great, Valve has of course priority.

**Comment by Pointedstick** [comment]
I've filed a KDE bug report to track this (https://bugs.kde.org/show_bug.cgi?id=406565) and put it on https://github.com/blue-systems/qa-topics/issues/8.
