### ISSUE TITLE
Discover: searching should be case insensitive

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#206]
esepcially with the virtual keyboard, i searched for Gltron with the first letter being suggested to be big, Discover found nothing.
gltron found gltron, even though really correctly the game name is glTron as in the description ;)

So i dont know when someone would search deliberately a different word spelling first letter capital then not.

**Comment by aleixpol** [comment]
Hi, this is a tricky one. It boils down to gltron not having any appstream data.

It's being found because we ask the distro for exact matches of package names and on debian* there is a `gltron` package.

I'd say the fix here is to get proper appstream metadata for the app, this way we'd get at least an icon, screenshots and a description.

**Comment by star-buck** [comment]
Appstream data, okay.
Still the other issue is that Discover should search non case sensitive, that is ignore any big capitals and issue the search after lowercase the search string.

**Comment by Pointedstick** [comment]
> Hi, this is a tricky one. It boils down to gltron not having any appstream data.
> 
> It's being found because we ask the distro for exact matches of package names and on debian* there is a `gltron` package.
> 
> I'd say the fix here is to get proper appstream metadata for the app, this way we'd get at least an icon, screenshots and a description.

We do? I thought we explicitly never showed packages? I think if we're going to show packages, we should explicitly support that use case and show all results, not just exact matches (possibly with an on-off switch in settings that defaults to off if we think this is too nerdy a feature) . Otherwise it's just confusing when you do a search that happens to match a package name exactly, and it and causes issues like this and https://github.com/blue-systems/plasma-5.17/issues/207.

And yeah, I agree that all searches should be case-insensitive. And also that the app in question just needs AppStream metadata :)

**Comment by aleixpol** [comment]
> We do?

Yes, it happens quite often that people want to install a specific package they saw in the interwebs. I used to get a lot of complaints. This makes the application more flexible without adding noise.

PackageKit::Daemon::resolve() can't take a case insensitive search argument because it's about finding the package name.

**Comment by star-buck** [comment]
Is there any package name start with a Capital letter?

**Comment by aleixpol** [comment]
In opensuse there seems to be and apt is definitely case-sensitive, not that it's much leveraged.

**Comment by Pointedstick** [comment]
> > We do?
> 
> Yes, it happens quite often that people want to install a specific package they saw in the interwebs. I used to get a lot of complaints. This makes the application more flexible without adding noise.

I don't like this kind of hidden magical behavior. IMO it falls into the category of trying so hard to be smart that we end up being dumb and causing bugs.

If we want to support the use case of people who want to use Discover to install packages, my strong preference would be for us to explicitly support it in the UI by doing something like always including packages in the search results, but sorting them into a separate category that's always below the apps in search results.

**Comment by star-buck** [comment]
That would be a good middle way, like not search hardcoded by case
insensitive, but also lowercase and add gltron to the list of suggested
packages uf the search term was Gltron for the sole reason of virtual
keyboard use without having VK correct guessing the likely usecase here.

**Comment by Pointedstick** [comment]
Got an upstream bug report for this: https://bugs.kde.org/show_bug.cgi?id=413988

Is there anything we can do here in Discover, or do we need PackageKit changes to fully fix this?

**Comment by Pointedstick** [comment]
I investigated this today and found that the problem is in PackageKit itself. Its backend for Debian-based distros performs case-insensitive searches as expected, but does not do so for Arch- or openSUSE-based distros. I have filed upstream bug reports to track these issues:

https://github.com/hughsie/PackageKit/issues/354 (openSUSE)
https://github.com/hughsie/PackageKit/issues/355 (Arch)

**Comment by aleixpol** [comment]
>  Its backend for Debian-based distros performs case-insensitive searches as expected.

Well no. This bug report is from a debian-based (aptcc) distro.
It's because resolve isn't case insensitive. It's different issues.

The one in Arch/openSUSE is probably more fixable than the issue at stake here.

**Comment by Pointedstick** [comment]
Can you help me understand the difference vs search and resolve in this context?

**Comment by aleixpol** [comment]
`resolve` looks for packages with a certain package name. `search` looks for strings in name, description etc.

**Comment by Pointedstick** [comment]
Shouldn't we always have the right name by the time we feed it to `resolve`? We use `search` which is case-insensitive to find the full list, then the user selects a result and that eventually gets passed to `resolve`?

**Comment by aleixpol** [comment]
> Hi, this is a tricky one. It boils down to gltron not having any appstream data.
> 
> It's being found because we ask the distro for exact matches of package names and on debian* there is a `gltron` package.
> 
> I'd say the fix here is to get proper appstream metadata for the app, this way we'd get at least an icon, screenshots and a description.

I tried to explain it here in the first comment. `resolve` is the actual exact match request.

**Comment by Pointedstick** [comment]
For the case of wanting to install packages by name, instead of passing the search string straight to `resolve`, could we first do a `search` so that we can find matches that don't have identical casing, and then pass that/those to `resolve`?

**Comment by aleixpol** [comment]
We are already doing this. `resolve` is only called if search is empty.
Note it's a search on appstream, not on PackageKit.

**Comment by Pointedstick** [comment]
I'm feeling quite stupid for not understanding this. But it seems like case-insensitive package matching should be possible somehow.

...or we can ditch the current somewhat confusing approach of showing packages only for exact text matches (case insensitive or not) and just show all package matches, either in a separate category below everything else, or optionally, based on a user-facing setting.

**Comment by aleixpol** [comment]
Let's discuss this in Gehrden next week side by side. :)

**Comment by Pointedstick** [comment]
Aleix and I dug into this (well, Aleix explained things in small words so I could understand :) ) and we discovered that the solution here really is for gltron to get some Appstream metadata. Without that, the only way to find it is by searching for its exact name that must be case-sensitive. Discover's search is already case-insensitive for apps that do have AppStream data, but we can't do this for the case of packages that lack it. This is a technical limitation that we can't really work around.

So we need a Debian packager to make some Appstream metadata for gltron on Debian, and then ideally submit it upstream so everyone can benefit from it.
