### ISSUE TITLE
ghns wallpaper: first opening shows "latest", but sorting is most downloaded

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#228]
when switching sort option back and forth,it actually shows latest fine

**Comment by leinir** [comment]
Good catch - patch is on invent, and while not /quite/ as trivial as the other one, it's... still pretty simple :)

**Comment by star-buck** [comment]
Here is hope the patch "just" shows correctly the latest ones first. ;) The
"Most downloaded" is actually the worst to show default, as its a
self-fullfilling prophecy, which inno way relates to the quality. In the
latter intent, would be better to show highest rating default. But best as
in fresh is latest, even though it means we need to be quick to fight
unwanted content, or simply could do a trick of a db delivery delay of
24-48 hours for ghns. Just adding these 2cents food for thought...

**Comment by leinir** [comment]
Hmm... The patch actually corrects the behaviour (which was more that the UI doesn't reflect the internal state), but also yes, i think  we do probably want newest first - also at the very least in part because that's what the rest of the KNewStuff codebase implies, so... yeah, i'll just do a quick wiggle for that one :)

**Comment by leinir** [comment]
Done and done :) https://invent.kde.org/frameworks/knewstuff/-/merge_requests/9

**Comment by Pointedstick** [comment]
Just to register my opinion here, I think whether you want to see newer items or potentially better rated/most downloaded things depends on the character of what thing you're looking at. For wallpapers or icon themes, newest probably makes the most sense since you're looking for fresh, interesting new things. But for something more complicated or which could be potentially buggy like Plasma widgets or KWin scripts, you're more likely to be interested in what's popular or rated well, which is generally an indicator that it works well.

Just my own two cents, and I don't have a super strong opinion here so I will support whatever changes folks think are best. :)
