### ISSUE TITLE
Official bug tracker for Plasma 5.9

### ISSUE THREAD

**Issue by UralZima** [blue-systems/plasma-5.9#73]
Hello. Can this github repo be considered as official plasma 5.9 bug tracker? bugs.kde.org seems very outdated and unorganized, most of parts have 4.14 version, and plasma 5.4 is latest version available for reporting. It is also very hard to decide, which section to choose for reporting. 

Please help me understand the official way for bug reporting in Plasma 5.

**Comment by star-buck** [comment]
Hi Ural.

Sorry, but this is not an official bug tracker. This is like Suse keeping
track of issues related to Blue Systems products, e.g. Netrunner. Of course
it might likely overlap with most other Plasma installs, or might be
specific because of components or customizations done in those products.
So please add any bug you experience with your distro related fo plasma to
your distros tracking system or the official bugtracker, which is as you
rightly pointed out bugs.kde.org.

Thanks for your interest and effort, as we're all in for the same goal: to
make plasma the best.

**Comment by UralZima** [comment]
Thanks for clarifying things out. 
It seems that bugs.kde.org was updated and contain latest versions, just some mess with selecting category.
I thought this was a bug tracker, because I read these two links https://github.com/blue-systems/plasma-5.4/issues/48  https://github.com/blue-systems/plasma-ideas/issues/35  and saw many people discussing it there, not on bugs.kde.org.

I think you need to add this to readme.md:
Please report bugs to official plasma bugtracker: http://bugs.kde.org

**Comment by star-buck** [comment]
Added to readme, thanks for the tip!
