### ISSUE TITLE
[samba-mounter]: shows smb:// default, but when clicking on the folder to scan network gives error

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.9#97]
as seen here on the latest odroid C1 img:
![snap 2017-10-03 at 11 03 01](https://user-images.githubusercontent.com/840070/31117631-dab332ba-a82a-11e7-809c-7fc5e6ae0b80.png)

**Comment by star-buck** [comment]
Dolphin: Network - SambaShares seems to have the same problem:
when entering smb:// in the adressbar, it adds a third "/" to it and fails.
when entering an ip like e.g. smb://1.2.3.4 it works in putting the added "/" at the end, so it reads:
smb://1.2.3.4/

**Comment by davidedmundson** [comment]
Fixed.
https://phabricator.kde.org/D8141

Note: If you were getting this error, you /might/ now just get this one instead "Unable to find any workgroups in your local network. This might be caused by an enabled firewall."
But at least that will be a correct message and not involve incorrect redirecting.

**Comment by shadeslayer** [comment]
Patch was pushed into DCI, will land in the next image

**Comment by star-buck** [comment]
seems fixed
